#include <cstring>
#include "Perf.h"

int main() {
    std::vector<PerfEvent> myEvents = {
      {PERF_TYPE_HARDWARE, PERF_COUNT_HW_CPU_CYCLES},
      {PERF_TYPE_HARDWARE, PERF_COUNT_HW_INSTRUCTIONS},
      {PERF_TYPE_HARDWARE, PERF_COUNT_HW_CACHE_REFERENCES},
      {PERF_TYPE_HARDWARE, PERF_COUNT_HW_CACHE_MISSES},
      {PERF_TYPE_HARDWARE, PERF_COUNT_HW_BRANCH_INSTRUCTIONS},
      {PERF_TYPE_HARDWARE, PERF_COUNT_HW_BRANCH_MISSES},
      {PERF_TYPE_HARDWARE, PERF_COUNT_HW_BUS_CYCLES},
      {PERF_TYPE_HARDWARE, PERF_COUNT_HW_STALLED_CYCLES_FRONTEND},
      {PERF_TYPE_HARDWARE, PERF_COUNT_HW_STALLED_CYCLES_BACKEND},
      {PERF_TYPE_HARDWARE, PERF_COUNT_HW_REF_CPU_CYCLES},

      {PERF_TYPE_SOFTWARE, PERF_COUNT_SW_CPU_CLOCK},
      {PERF_TYPE_SOFTWARE, PERF_COUNT_SW_TASK_CLOCK},
      {PERF_TYPE_SOFTWARE, PERF_COUNT_SW_PAGE_FAULTS},
      {PERF_TYPE_SOFTWARE, PERF_COUNT_SW_CONTEXT_SWITCHES},
      {PERF_TYPE_SOFTWARE, PERF_COUNT_SW_CPU_MIGRATIONS},
      {PERF_TYPE_SOFTWARE, PERF_COUNT_SW_PAGE_FAULTS_MIN},
      {PERF_TYPE_SOFTWARE, PERF_COUNT_SW_PAGE_FAULTS_MAJ},
      {PERF_TYPE_SOFTWARE, PERF_COUNT_SW_ALIGNMENT_FAULTS},
      {PERF_TYPE_SOFTWARE, PERF_COUNT_SW_EMULATION_FAULTS},

      {PERF_TYPE_HW_CACHE, PERF_COUNT_HW_CACHE_L1D},
      {PERF_TYPE_HW_CACHE, PERF_COUNT_HW_CACHE_L1I},
      {PERF_TYPE_HW_CACHE, PERF_COUNT_HW_CACHE_LL},
      {PERF_TYPE_HW_CACHE, PERF_COUNT_HW_CACHE_DTLB},
      {PERF_TYPE_HW_CACHE, PERF_COUNT_HW_CACHE_ITLB},
      {PERF_TYPE_HW_CACHE, PERF_COUNT_HW_CACHE_BPU},
      {PERF_TYPE_HW_CACHE, PERF_COUNT_HW_CACHE_NODE},
    };
    Perf p(myEvents);
    return 0;
}